language: generic
if: (branch = develop AND (type = cron OR type = api)) OR (branch = master AND type = api)
services:
- docker
before_install:
- .travis/check_branch.sh
- .travis/docker/setup.sh 
env:
  global:
  - TRAVIS_GO_VERSION=1.13.1
  - secure: dP4dHpULJGNSnFd1r66xgZow7+KMY48HeRcBYklQpjlfziqzjouIkdJ0jCT3NQdWgikDwiD0jqGwC1ROtzeypKrLmAF9nq/kIQEp6v0UwDE3TmGyuODP1rjcgkxrMFxFqNOVCmkhnmR1N0etAXYcdDruu5FKAxbhxxiD/W0p5Qo8OqS4oo7u7UZgb8fdqmZDQexOLx3DbHaWR/AK5TIiNCTa9sIq67xRVM5q5PoBpdn3S80UWfYprs4UwL8E6tmFH0Ki3oH1rJ/79AGP4k3ltexltXeE37dtTSXkddb/89f/rjUGDBgFS7vn++X3yLbcAq5FiMhw2nHLQzFyXzjxq0fXroutFqsSOup7bDDwSrFUKlFnTKfauxDWz3RUpDVnSMvvAAot6pbM29xL7TMejYDBdazjVS7jNOORwCp2+X0Ha7PJhzMNRmoU56Kob9I5+WRCNE4pXXOfBQ9s0YsMDr9vo5YvdGx51rB90bIzNzNA52Apkj4Tn9kMdv40qyYuajt5azaTfqjoZVEzBwhCBJF/wTFAJkR5M2O8SMfYOBcD2PLW8AMV3HC12l1YWPIWpyx08S+73FR5PQy17VXRlVkE4bMQ1xG0b4s7io3O2FHFca2f2i+tSmBvL/5MyekcZpjmruMX7BImM5tVt7gARnAWCNA9SgdZ7cMKrkhlHhI=
  - secure: ogoAVlLlTx63mBzyNObdUtVqIX42KySaR+TipHvZmYIg1nyqQu/84wQy1bNk1oAEgi8qd6BS2FBOl/y8W98NJjGPa0Opn7xMiV7fuXCBMlwCDxADUFwk5l/ZSZGZoEp8pPtiqaiKWG7Kjm91VtWLjTUHYGBJSly2bKRAUlWsZoesMPZ6frnqdPp2ryOCdX0ulqMdgk+BaJGU3G7ix2z+I+Plwm5qLXDdx+1zGrP194d+l+anEIweNKV3vsD69vvXj7f1aVpMe1lm9OQ24BVMue2xYPkRdLxkTJ1cVe/R0x2ErlQruLC3Qxq9OLSyy1vJ3enXzU+xp1HmsaAbGlikzAGBvpxzdAwtJT4RgarMatYMm5XeFUsF5CfXuwWOAifOhYm3k+TkSX+nK/TnIB28iWnM/u86zdG80NN18A8v6DP9feEk3CMi3rB9qSt+hUP5neXfpz93xG4Ku9JboDh4ZUUO+bNTx+XEt3af75rlYP4lhoCcKlCyKfgVGfOC2WZPSDhOm40KH8NB4zlQKX/vD2K3qTKZmj7pQyCJud+sRbeUvRJdx7CwD75MtDKn7gvThbvK/HEw12VoHL9AvE4lFC7KE/osdYkfG6s9sHZLn5LYwomI2paLVdiTlzq+mxYGQlMOVhMDuv9MvP8AgSFngRSq3YxcniyIBNRnO20PZ0g=
jobs:
  include:
############### GITHUB SUBMODULES ###############
    - stage: update_submodules
      script: .travis/github/update_submodules.sh -y --branch $TRAVIS_BRANCH
############### DOCKER DEPLOYMENT ###############
    - stage: docker_deploy_base
      script: travis_retry ./docker/base/deploy.sh -y --branch $TRAVIS_BRANCH 
    - script: travis_retry ./docker/base/deploy.sh -y --branch $TRAVIS_BRANCH --slim
    - script: travis_retry ./docker/base/deploy.sh -y --branch $TRAVIS_BRANCH --alpine
# -------------------------------------------------------
    - stage: docker_deploy_logicmodule
      script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8
    - script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8 --slim
    - script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8 --alpine
    - script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11  
    - script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11 --slim 
    - script: travis_retry ./docker/logicmodule/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11 --alpine
# -------------------------------------------------------
    - stage: docker_deploy_dsjava
      script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8
    - script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8 --slim
    - script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk8 --alpine
    - script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11
    - script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11 --slim
    - script: travis_retry ./docker/dsjava/deploy.sh -y --branch $TRAVIS_BRANCH --ee jdk11 --alpine
# -------------------------------------------------------
    - stage: docker_deploy_dspython
      script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.6 
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.6 --slim
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.6 --alpine
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.7 
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.7 --slim
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.7 --alpine
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.8 
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.8 --slim
    - script: travis_retry ./docker/dspython/deploy.sh -y --branch $TRAVIS_BRANCH --ee py3.8 --alpine
# -------------------------------------------------------
    - stage: docker_deploy_client
      script: travis_retry ./docker/client/deploy.sh -y --branch $TRAVIS_BRANCH
    - script: travis_retry ./docker/client/deploy.sh -y --branch $TRAVIS_BRANCH --slim
    - script: travis_retry ./docker/client/deploy.sh -y --branch $TRAVIS_BRANCH --alpine
############### MARENOSTRUM DEPLOYMENT ###############
    - stage: marenostrum_deploy
      before_install: 
         - .travis/check_branch.sh
         - .travis/singularity/setup.sh && .travis/marenostrum/set_ssh.sh
      script: travis_retry ./.travis/marenostrum/deploy.sh -y --branch $TRAVIS_BRANCH
notifications:
  email:
    - commiter:
      on_success: change
      on_failure: always
    - cron:
      if: type = cron
      recipients:
        - support-dataclay@bsc.es
      on_success: change
      on_failure: always