version: 2.6.dev.build{build}
branches:
  only:
    - develop
build_cloud: Docker
image: Linux
skip_tags: true
skip_branch_with_pr: true
environment:
  DOCKER_USERNAME:
    secure: d9s0OSEPlE156nPrhrsNnA==
  DOCKER_PASSWORD:
    secure: TO42yeTsoNEkuoRQ9ES7MQ==
  MN_PRIVATE_KEY:
    secure: oazgZGq8Yz6SLTkiORUNZyBqWY0ZZ4hzNJjx2IvWBtd6m4jzhD88TVAmnfCn955bV+emkcjS4Q6Jt4voWkKBu8jnOW+ww396LQAdBmu2j9LZ0RYikSoTRfYshrnracLSToIuU96lhxfrpK0/M8wwwGYR2euadZBIQaQVSbUN7x1N2cQq+6yO1UMUflGAANKJw0T8JL52DYr9WCMt1meN5BhAzn/DMxIsMIexz0J5O88VyXfLGfUutD/XUT/eaQxg2XASZiw0Ra9C8IYPSsUT1M5C05sHUkvCwMpPdz9estZtrM4cVqJ1S7p3DNmz/kowCOz/qBF5QgAlnK4uDdIb+9l26bjCLog2dyZG3Zx+Gu0peFdi92MEBED6Mcrtuj7teRejpe79whEFFzR1gQqCL+ahhYMQ61yvrqVjmuaXHoF98M/6GzwEFgZSkk7vgE2giM7pJPgAOjyKLHeM4pZozR6879RUW1LAXUj40t9eQ+hHv0XIMhDaAJuYthiH8CZEf8tr24SNv0ZnTSttkf4SoXvydA5vCkD5DXTkasjRyqNoCUFQNcj03uUtqN5TzDx3JaK/MaxlQkDsVYbrBTRTmcHNIWD/0w11aZp1ZOzNJcWxs8lW5RnXnLVbPJCHACzximUeVYb64pLFqpRIqN4ov8jwTMpbqA2B4HsDrxnqV4fhQOeZZZfi1imgJuX9AzfhFoVnyp/lP2RWkMRvWBaNwUVJ4wPXc+Jdank5OQ0PMeM5lKnAyxCHI0vuiAm1htM0knGIwHRyVaC7Cp/vrBd+lEzyU1aABCevyBeFs8jDUBsnNtvNNheQ6KkfYKV3oy9ar0J8f+jxYh8OHijxGH5sND+9DnnkY9DIFLyeh2SN2wQxcg0t9dczH3GBUnWdzw1K2EByKlrpnQ9KH8R3XmB5mjYjKX0Qa808LSpcpccN36uLt8LPuhdRea8ak6ZFD9orouZfDzU1BK/c17KemkzuDoYIjb2KfKz8zSI8oD80Rn9vjtQ44RqCOE3vRNSH1+U5NgL6MgjKJCSNYmId0TnnYykPWuRbzQfBVXhxi7blIVctW4I/oH1ci1j9YoQvZspReHcR4689tg7+IlsML/FoYYL6/O875k6P3shIlPEtMY9qqgBUJmqiW8t1q+sE4j1NsCveYMq07OagAGQzg4AsD/W9pgEXwp4MM1xPATURUn30+DHUf3mhwaN7cZQ2dfgcAXPrsIhlszWhL9ZEBGfjCSWccKxXn03k4m4lPHSflZLvk0er3P704Kdanfyjt8buyzobm0HDXqS9j3fJqfMTU/O9zQ+qzq9qHM7wqsu1J2gOy4Ubz6ZcJV3kXiUpaIW/SXXpiLWeoNEILwZXs17kBrVezDzR0A90q+e3UmVhw/lF6dUUmm+mV/6U8yx+HR8J8r6e4i//RIu5kMMoTXGAum6pd4lwps3NJSzjVEuMOZUpSDzioInKoFYPeAlLKQMRv3XqUiV2f16w4jR+AXGqIIt48xO6fRADXykRk5VV6S79iF24kZNyhLBwwJRs/SwFu8WOtalu/izuHnY7iy4gUKi1Cu6E/CWLE8xg610Ry5CUi2NPMQGbsvR2PqGHu/4YeafaqgmHeBV5styv79doqpkuCAV9W1I9e0pzRJfVaIe4zF1a9ai40jbqdEV95rm5qAzNW3mrXwojqG3NWr/zJqLV2NruBh1GjNMhtVF40oDywpWEKRMhjsah1ir8HSl7hWKxv8J479RWKO1EXp0MRaXkiyXIpYi0hcr82szgUFuxpW3gXWLlspcQMKFq1N1GM3GCHi2e5RMxpnInDJQn+tp5SGi21Rgdu8DLsj3dLOXirD+Na3sbX0FAMsUKCIVrrDzFFb7UTxFE517Cw0250WuBGFZDjxB2NM9/rFEDIugRcjJhXXGiNvVTmZrphPJJ5VLUWZgljRPpJlSAXVaG3YZ7K4MYruNV0BzzjRy74BXRM4ggk2QxQFEurlIVEnjp43ov1av2bdLkYBICfgL8RKgeu35qejTPBbUxamtgFStOyClRxVeiBEgL1RcRGE3DEshjNtfWFHyvTEE1gphIRaSXdZpm8KfRbpPvKUOB6n4B1g5gO9kaVHqxKkRnIw2KIYoqTc92jUocW933oQb9DyVUy3UWhflv054zo8Hr95jrF2FdWksfSQjw79G06pEJWvW0yAakmT77eD7wu1IMD78kwTrVztRC6xSR7A/MYGfSYaikdRzp7adg+HeZLWbgVFvp9WpTBXsqqVKfHTAdOv6CDSZxL/1MAYqnYgmL/42A8VkhwGSVwZPbqiHEIpwyzLmwGGUwR8HJvjlJ3Bw+HfSBqDSW9+5zIJ5LRdbT6Dzhn5Woreda/96rMwDi5bokwYBAtTGvK8ao1006ledQ5Z0C4bHBljrY6fs38VY+XCl65HNOn1ZEKSzdr+mtAuI90MRk8+FXAz75f1DlBwvU7qDzBLF2stQX8rHbZ3I9biLu0oybrLxtS5bk0oqNXdFxB15zdEqTFppVFHn5p7v9YE61ugKUHx23GHhekvHpAOWPhvzU6jJ3NmdaNOpeFTU+JTHoGVDi6uyGiRMHumm9YNP4LKS93v1AbA+761c03NmvNriM4LMCGpFVjn1d1v6vO9g66lfREIOXRxd8tZSGj8W+PwXzdRgSDL9mOFo+J6pP9+iOCbf9i+22+7+UtJqMcrgjDzjUKnutFXOmf3HDIwMpHKdlJVC4InHZZRcZbov0Y4+tpu20ENe4Aw3b8hsSG0fuWrDMGQPZ1K6BHtmYGGup9aFzV6aVRWqhiEAStghYN5CHIFcoY6/aOLgwD5bVMHMLKKspUtGNuHbzJWL4BvmTbM7fScYrVYdx07LeLwdMh9n+ixL8yYi7jHVSgNoYQ+PDVZHjshGVMqfLCxybDcHCQaiEvJvZ5d8o8phu6LeHD7hjSbobD5xle+BlVT7CZ4Sm5No9/bgb27QVETIocgffFKDGOdab9AqEdocEJrlH+D0HqkbScKm5Zx+p13WdAwuw2LBjQQMUA54AvgOCrT+PjuzqNFSwTSbdrDO/QzxLxOcpnqJGP2rBAn+4EynNfxjVPyfWxWLHiucA330rkyaxd2ABeTACskypBxBnacRktvL74UDDGawkE+Q4qJrrU55Uvq9z8hn5sFRpBtIjGeb0X2qUS69qbA6oB4Hy5b79d2wUBWaNclO9MUOax2HsAOf7nZ+59eY/Z0zeycUpbCgA+JW4T7GOq2BwOlOl0rw27Ed75C4hxwGBehrlSZy2BOk1sVdCjUj1A4vmUfXWQesFc0aMdz7HHTYHknwmTQDWrTa89mZ9L0QWB2Ca5E962X/0ofTMjvAmAMNTvtxqK+CHP8VyJb15InJ33bul9Cid5SSW5HRcHy8QpUHNnaPSZANBLYY9n7xbwhj428nxje5EVP+UiBJnYss4+Byju60+soUnmlGJ+u5k3blRZO20nn6VjqRs3CMphizSLsahg8TCtJYyspnlD3n2PDqG34atRQHnRm+2IbB9dYsMQI7+evWe123udvxw0cSUKvzjc1UKNebXj/XDdb9AwCgNh2xIFPx8FDHRnldjp5DNTBb73gjrwr8R/7UYe5GCXcPH1zq3mbQqce8IcwaGurOAjPaPYneKacAbgn5XIIynRBdxwvSy/yepyfrSQV1V8yXqvqmAZ6LWEWYberRtbi+r8zBqLFamHITAYdte1orwI/OIAVJU5NPd0OVTgt1hZ/3dfLx/v6vG2UpRnEL+AjOZhkoldGEV36MwR5r8LjNCc430DvXCeJg97Yjv6sLjsqYjlh7yt7NudFeZs1k/l1SE1CXK87v9qnkwctp9XRV+K6LgGKqCed9cjtBFdu1mV7xUlCTy86ty3WiFaiK+C23Y88tG8Y/QM9o404SvRfk0qxFnqJlUzRmQVm1HSsPVVDRXSl/YbH54cEst7Yi/VMAoS2PbcwqklXNeNTOI9dM8WspA+DnbP9mvl+TR+g1kmNiR5c2w0oHF6WpXcFg5MgweCnXgKL80l663KKD4AdDVvSIm08Svihgx7ml5fD3DNFN5BzOTpFgOFffSFUn7lPUe3ZIw/eKwalRgccTiiShUbb55fwTNB4jUbHqOfJJDuOcHF0G6AG5t/ksvqppesqZh9s/dkhkIbONLjua/rViav0RQHOZ1VrBO6mFmq/AjOs980jWV5ABZLed/7ntNi6cSrxbGCMz3C+jOH5YyX4nqx20M3E0FTf2KNmX+Y6PTOlMjZg==
  matrix:
# LOGICMODULE ALPINE ------------------------------------------------------------------------
    - job_name: Deploy logicmodule alpine jdk11
      job_group: logicmodule
      job_depends_on: base
      dataclay_image: logicmodule
      image_type: alpine
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging
# DSJAVA ALPINE ------------------------------------------------------------------------
    - job_name: Deploy dsjava alpine jdk11
      job_group: dsjava
      job_depends_on: logicmodule
      dataclay_image: dsjava
      image_type: alpine
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging
# DSPYTHON ALPINE ------------------------------------------------------------------------
    - job_name: Deploy dspython alpine py3.6
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: alpine
      execution_env: py3.6
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy dspython alpine py3.7
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: alpine
      execution_env: py3.7
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy dspython alpine py3.8
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: alpine
      execution_env: py3.8
      docker_image: bscdataclay/continuous-integration:packaging
# CLIENT ALPINE ------------------------------------------------------------------------
    - job_name: Deploy client alpine
      job_group: client
      job_depends_on: dspython
      dataclay_image: client
      image_type: alpine
      docker_image: bscdataclay/continuous-integration:packaging
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
for:

  -
    matrix:
      only:
        - job_group: base
    build_script:
      - /init-scripts/init.sh
      - ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type

  -
    matrix:
      only:
        - job_group: logicmodule
    build_script:
      - /init-scripts/init.sh
      - ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dsjava
    build_script:
      - /init-scripts/init.sh
      - ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dspython
    build_script:
      - /init-scripts/init.sh
      - ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: client
    build_script:
      - /init-scripts/init.sh
      - ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type