version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
environment:
  DOCKER_USERNAME:
    secure: d9s0OSEPlE156nPrhrsNnA==
  DOCKER_PASSWORD:
    secure: TO42yeTsoNEkuoRQ9ES7MQ==
  DOCKER_CLI_EXPERIMENTAL: enabled
  MN_SALT:
    secure: A2CVXopXaMJuIZw+vkdiklA4nLKgFmjW9W3PpofFBi1elXHhnPaoHbdOv6Rk1NHP04O7y8D7l21XzmPgYtZF8g==
  MN_SECRET:
    secure: fOYbgYSg0A2yudFL4mi8glRpB/VlAdbf0Genq44vLws=
  matrix:
    # MN ORCHESTRATION ------------------------------------------------------------------------
    - job_name: Deploy mn orchestration scripts
      job_group: mn_orchestration
    # MN LOGICMODULE ------------------------------------------------------------------------
    - job_name: Deploy mn logicmodule jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: --ee jdk8

    - job_name: Deploy mn logicmodule jdk11
      job_group: mn_logicmodule
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: --ee jdk11
    # MN DSJAVA ------------------------------------------------------------------------
    - job_name: Deploy mn dsjava jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: --ee jdk8

    - job_name: Deploy mn dsjava jdk11
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: --ee jdk11
    # MN DSPYTHON ------------------------------------------------------------------------
    - job_name: Deploy mn dspython py3.6
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.6

    - job_name: Deploy mn dspython py3.7
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.7

    - job_name: Deploy mn dspython py3.8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.8
    # MN CLIENT ------------------------------------------------------------------------
    - job_name: Deploy mn client
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: client
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
#init:
#  - sudo apt-get install docker.io
for:

  -
    matrix:
      only:
        - job_group: mn_orchestration
    build_script:
      - |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v ${HOME}/.docker/config.json:/root/.docker/config.json:ro \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e MN_SALT=$MN_SALT \
          -e MN_SECRET=$MN_SECRET \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging-mn \
          ./hpc/mn/deploy_orchestrator.sh -y --dev
        docker logout
  -
    matrix:
      only:
        - job_group: mn_deploy
    build_script:
      - |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v ${HOME}/.docker/config.json:/root/.docker/config.json:ro \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e MN_SALT=$MN_SALT \
          -e MN_SECRET=$MN_SECRET \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging-mn \
          ./hpc/mn/deploy_image.sh -y --dev --singularityimg $dataclay_image $execution_env
        docker logout
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true