version: 2.6.dev.build{build}
branches:
  only:
    - develop
build_cloud: Docker
image: Linux
skip_tags: true
skip_branch_with_pr: true
environment:
  DOCKER_USERNAME:
    secure: d9s0OSEPlE156nPrhrsNnA==
  DOCKER_PASSWORD:
    secure: TO42yeTsoNEkuoRQ9ES7MQ==
  MN_SALT:
    secure: mfxxGVIGJAn/9bdDJuddZPelTGttAp5E/Zhp5gWAYMXK4vs0ZNG7Y1me51KAMohPm2LoBOlJJcXDiTzHArWHBA==
  MN_SECRET:
    secure: hSTFAA0tfcvWY5Z+UekLapymVeyo7HxGMW52TMM8O6g=
  matrix:
# MN ORCHESTRATION ------------------------------------------------------------------------
    - job_name: Deploy mn orchestration scripts
      job_group: mn_orchestration
      docker_image: bscdataclay/continuous-integration:packaging-mn
# MN LOGICMODULE ------------------------------------------------------------------------
    - job_name: Deploy mn logicmodule jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: jdk8
      docker_image: bscdataclay/continuous-integration:packaging-mn

    - job_name: Deploy mn logicmodule jdk11
      job_group: mn_logicmodule
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging-mn
# MN DSJAVA ------------------------------------------------------------------------
    - job_name: Deploy mn dsjava jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: jdk8
      docker_image: bscdataclay/continuous-integration:packaging-mn

    - job_name: Deploy mn dsjava jdk11
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging-mn
# MN DSPYTHON ------------------------------------------------------------------------
    - job_name: Deploy mn dspython py3.6
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: py3.6
      docker_image: bscdataclay/continuous-integration:packaging-mn

    - job_name: Deploy mn dspython py3.7
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: py3.7
      docker_image: bscdataclay/continuous-integration:packaging-mn

    - job_name: Deploy mn dspython py3.8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: py3.8
      docker_image: bscdataclay/continuous-integration:packaging-mn
# MN CLIENT ------------------------------------------------------------------------
    - job_name: Deploy mn client
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: client
      docker_image: bscdataclay/continuous-integration:packaging-mn
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
for:

  -
    matrix:
      only:
        - job_group: mn_orchestration
    build_script:
      - /init-scripts/init.sh
      - /init-scripts/init_mn.sh
      - ./hpc/mn/deploy_orchestrator.sh -y --dev

  -
    matrix:
      only:
        - job_group: mn_deploy
    build_script:
      - /init-scripts/init.sh
      - /init-scripts/init_mn.sh
      - ./hpc/mn/deploy_image.sh -y --dev