version: packaging.deploy.build{build}
build_cloud: bsccsdomci01
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
deploy_script:
  - |
      docker buildx rm dataclay-builderx
      docker exec -it registry bin/registry garbage-collect /etc/docker/registry/config.yml -m
      git submodule init
      git submodule update
      ./docker/deploy.sh --plain --images base
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true