version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
environment:
  DOCKER_USERNAME:
    secure: d9s0OSEPlE156nPrhrsNnA==
  DOCKER_PASSWORD:
    secure: TO42yeTsoNEkuoRQ9ES7MQ==
  matrix:
    # LOGICMODULE SLIM ------------------------------------------------------------------------
    - job_name: Deploy logicmodule slim jdk8
      job_group: logicmodule
      dataclay_image: logicmodule
      image_type: slim
      execution_env: jdk8
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy logicmodule slim jdk11
      job_group: logicmodule
      dataclay_image: logicmodule
      image_type: slim
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging
    # DSJAVA SLIM ------------------------------------------------------------------------
    - job_name: Deploy dsjava slim jdk8
      job_group: dsjava
      job_depends_on: logicmodule
      dataclay_image: dsjava
      image_type: slim
      execution_env: jdk8
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy dsjava slim jdk11
      job_group: dsjava
      job_depends_on: logicmodule
      dataclay_image: dsjava
      image_type: slim
      execution_env: jdk11
      docker_image: bscdataclay/continuous-integration:packaging
    # DSPYTHON SLIM ------------------------------------------------------------------------
    - job_name: Deploy dspython slim py3.6
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.6
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy dspython slim py3.7
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.7
      docker_image: bscdataclay/continuous-integration:packaging

    - job_name: Deploy dspython slim py3.8
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.8
      docker_image: bscdataclay/continuous-integration:packaging
    # CLIENT SLIM ------------------------------------------------------------------------
    - job_name: Deploy client slim
      job_group: client
      job_depends_on: dspython
      dataclay_image: client
      image_type: slim
      docker_image: bscdataclay/continuous-integration:packaging
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
#init:
#  - sudo apt-get install docker.io
for:

  -
    matrix:
      only:
        - job_group: logicmodule
    build_script:
      - |
        docker run -v $PWD:$PWD \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          --entrypoint /scripts/init.sh bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dsjava
    build_script:
      - |
        docker run -v $PWD:$PWD \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          --entrypoint /scripts/init.sh bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dspython
    build_script:
      - |
        docker run -v $PWD:$PWD \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          --entrypoint /scripts/init.sh bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: client
    build_script:
      - |
        docker run -v $PWD:$PWD \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          --entrypoint /scripts/init.sh bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type
