version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
environment:
  DOCKER_USERNAME:
    secure: BjCQHIN21F+sOx1mQICY5Q==
  DOCKER_PASSWORD:
    secure: 4tDbnFmVNXL6+VAwzvb61w==
  matrix:
    # LOGICMODULE SLIM ------------------------------------------------------------------------
    - job_name: Deploy logicmodule slim jdk8
      job_group: logicmodule
      dataclay_image: logicmodule
      image_type: slim
      execution_env: jdk8

    - job_name: Deploy logicmodule slim jdk11
      job_group: logicmodule
      dataclay_image: logicmodule
      image_type: slim
      execution_env: jdk11
    # DSJAVA SLIM ------------------------------------------------------------------------
    - job_name: Deploy dsjava slim jdk8
      job_group: dsjava
      job_depends_on: logicmodule
      dataclay_image: dsjava
      image_type: slim
      execution_env: jdk8

    - job_name: Deploy dsjava slim jdk11
      job_group: dsjava
      job_depends_on: logicmodule
      dataclay_image: dsjava
      image_type: slim
      execution_env: jdk11
    # DSPYTHON SLIM ------------------------------------------------------------------------
    - job_name: Deploy dspython slim py3.6
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.6

    - job_name: Deploy dspython slim py3.7
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.7

    - job_name: Deploy dspython slim py3.8
      job_group: dspython
      job_depends_on: dsjava
      dataclay_image: dspython
      image_type: slim
      execution_env: py3.8
    # CLIENT SLIM ------------------------------------------------------------------------
    - job_name: Deploy client slim
      job_group: client
      job_depends_on: dspython
      dataclay_image: client
      image_type: slim
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
#init:
#  - sudo apt-get install docker.io
for:

  -
    matrix:
      only:
        - job_group: logicmodule
    build_script:
      - |
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dsjava
    build_script:
      - |
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: dspython
    build_script:
      - |
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type --ee $execution_env

  -
    matrix:
      only:
        - job_group: client
    build_script:
      - |
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e DOCKER_USERNAME=$DOCKER_USERNAME \
          -e DOCKER_PASSWORD=$DOCKER_PASSWORD \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging \
          ./docker/$dataclay_image/deploy.sh -y --dev --plain --$image_type
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true