version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 4
environment:
  MN_SECRET:
    secure: fOYbgYSg0A2yudFL4mi8glRpB/VlAdbf0Genq44vLws=
  MN_SALT:
    secure: 36ZGkh6PxmQeiJfk3ErfZlpGGNXYLROluqkTmcByCrdRzAU3UjcSHJhsho5kLBOYHza4nGSLhRsZcSbu1EC5vA==
  matrix:
    # MN ORCHESTRATION ------------------------------------------------------------------------
    - job_name: Deploy mn orchestration scripts
      job_group: mn_orchestration
    # MN LOGICMODULE ------------------------------------------------------------------------
    - job_name: Deploy mn logicmodule jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: --ee jdk8

    - job_name: Deploy mn logicmodule jdk11
      job_group: mn_logicmodule
      job_depends_on: mn_orchestration
      dataclay_image: logicmodule
      execution_env: --ee jdk11
    # MN DSJAVA ------------------------------------------------------------------------
    - job_name: Deploy mn dsjava jdk8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: --ee jdk8

    - job_name: Deploy mn dsjava jdk11
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dsjava
      execution_env: --ee jdk11
    # MN DSPYTHON ------------------------------------------------------------------------
    - job_name: Deploy mn dspython py3.6
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.6

    - job_name: Deploy mn dspython py3.7
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.7

    - job_name: Deploy mn dspython py3.8
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: dspython
      execution_env: --ee py3.8
    # MN CLIENT ------------------------------------------------------------------------
    - job_name: Deploy mn client
      job_group: mn_deploy
      job_depends_on: mn_orchestration
      dataclay_image: client
# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true
#init:
#  - sudo apt-get install docker.io
for:

  -
    matrix:
      only:
        - job_group: mn_orchestration
    build_script:
      - |
        echo $MN_SALT
        echo $MN_SECRET
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e MN_SALT=$MN_SALT \
          -e MN_SECRET=$MN_SECRET \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging-mn \
          ./hpc/mn/deploy_orchestrator.sh -y --dev

  -
    matrix:
      only:
        - job_group: mn_deploy
    build_script:
      - |
        docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e MN_SALT=$MN_SALT \
          -e MN_SECRET=$MN_SECRET \
          -w=$APPVEYOR_BUILD_FOLDER \
          bscdataclay/continuous-integration:packaging-mn \
          ./hpc/mn/deploy_image.sh -y --dev --singularityimg $dataclay_image $execution_env
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true