version: packaging.mn.build{build}
build_cloud: bsccsdomci01
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
deploy_script:
  - |
    git submodule init
    git submodule update
    ./hpc/mn/deploy.sh
notifications:
  - provider: Email
    to:
      - support-dataclay@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true