/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_bsc_dataclay_extrae_DataClayExtraeWrapper */

#ifndef _Included_es_bsc_dataclay_extrae_DataClayExtraeWrapper
#define _Included_es_bsc_dataclay_extrae_DataClayExtraeWrapper
#ifdef __cplusplus
extern "C" {
#endif

/****** ADDED ******/
#define UNREFERENCED_PARAMETER(a) {(void) (a);}
#define UNREFERENCED(a)           {(void) (a);}

/*
 * Class:     es_bsc_dataclay_extrae_DataClayExtraeWrapper
 * Method:    Flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_dataclay_extrae_DataClayExtraeWrapper_Flush
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
